"""ACIC 2016 competition loader (Dorie et al., 2019) — semi-synthetic, continuous outcome.

Third independent continuous-outcome family (R4 reviewer request W1): real covariates
from the Collaborative Perinatal Project (n=4802, p=58, mixed numeric/categorical) with
simulated treatment and continuous outcomes from the official competition DGPs; the true
CATE (mu1 - mu0) is known.

The instances are generated by the official R package ``aciccomp2016`` via
``scripts/acic2016_generate.R`` (settings {1,4,5,9,21,25,27,28,31} x replicates 1-2 — a
deterministic stratified subset of the heterogeneous-effect settings; see the R script
header). If the cached CSVs are absent this loader shells out to ``Rscript`` and
generates them; without R installed it raises with install instructions.

Treatment is *observational* (confounded by design), matching IHDP handling: propensity
is left to be estimated on the training folds by the runner.
"""

from __future__ import annotations

import logging
import shutil
import subprocess
from pathlib import Path
from typing import Optional

import pandas as pd

from uplift_bench.data._cache import get_data_dir
from uplift_bench.data.base import DatasetMeta, UpliftDataset

log = logging.getLogger(__name__)

SETTINGS = (1, 4, 5, 9, 21, 25, 27, 28, 31)
REPLICATES = (1, 2)

_REPO_ROOT = Path(__file__).resolve().parents[3]
_GEN_SCRIPT = _REPO_ROOT / "scripts" / "acic2016_generate.R"


def _ensure_generated(data_dir: Path) -> None:
    wanted = [data_dir / f"setting{s:02d}_rep{r}.csv" for s in SETTINGS for r in REPLICATES]
    if (data_dir / "x.csv").exists() and all(p.exists() for p in wanted):
        return
    if shutil.which("Rscript") is None:
        raise RuntimeError(
            "ACIC 2016 cache is missing and Rscript is not installed. Install R plus the "
            "official package (see scripts/acic2016_generate.R header), then run:\n"
            f"  Rscript {_GEN_SCRIPT} {data_dir}"
        )
    log.info("Generating ACIC 2016 instances via %s ...", _GEN_SCRIPT.name)
    subprocess.run(
        ["Rscript", str(_GEN_SCRIPT), str(data_dir)],
        check=True,
        capture_output=True,
        text=True,
    )


def load_acic2016(
    setting: int = 1,
    replicate: int = 1,
    data_dir: Optional[Path] = None,
) -> UpliftDataset:
    """Load one ACIC 2016 (setting, replicate) instance.

    Parameters
    ----------
    setting:   parameter row of the official 77-setting grid (must be one of SETTINGS)
    replicate: simulation seed within the setting (1 or 2 in the released cache)
    data_dir:  override cache directory
    """
    if setting not in SETTINGS:
        raise ValueError(f"setting must be one of {SETTINGS}, got {setting}")
    if replicate not in REPLICATES:
        raise ValueError(f"replicate must be one of {REPLICATES}, got {replicate}")

    data_dir = Path(data_dir) if data_dir else get_data_dir() / "acic2016"
    data_dir.mkdir(parents=True, exist_ok=True)
    _ensure_generated(data_dir)

    x_raw = pd.read_csv(data_dir / "x.csv")
    # One-hot encode the categorical CPP covariates (deterministic column order).
    X = pd.get_dummies(x_raw, drop_first=True).astype(float)
    X.columns = [str(c).replace(" ", "_") for c in X.columns]

    sim = pd.read_csv(data_dir / f"setting{setting:02d}_rep{replicate}.csv")
    treatment = pd.Series(sim["z"].astype(int).to_numpy(), name="treatment")
    outcome = pd.Series(sim["y"].to_numpy(), name="outcome")
    ite_df = pd.DataFrame(
        {
            "ite": (sim["mu1"] - sim["mu0"]).to_numpy(),
            "mu0": sim["mu0"].to_numpy(),
            "mu1": sim["mu1"].to_numpy(),
        }
    )

    ds = UpliftDataset(
        X=X,
        treatment=treatment,
        outcome=outcome,
        propensity=None,  # observational by design; estimated on train folds
        ite=ite_df,
        meta=DatasetMeta(
            name=f"acic2016_s{setting}r{replicate}",
            n=len(X),
            n_features=X.shape[1],
            treatment_fraction=float(treatment.mean()),
            outcome_base_rate=float(outcome.mean()),
            has_ground_truth_effect=True,
            extras={"setting": setting, "replicate": replicate},
        ),
    )
    ds.validate()
    return ds
