"""Fold-level resolution analysis of the capped-RCT Qini leaderboards (R28).

The Criteo 100K probe showed that at the released 10K evaluation cap the six
meta/forest learners' Qini gaps are small relative to fold-to-fold variation, while at
100K the field separates -- i.e. the cap, not the models, limits ranking
resolution. This script generalizes the check: for every marketing RCT it
reports each model's fold-level Qini mean +/- SE and the z-separation of the
leader from every other model, so readers can see which leaderboard separations
are real (Lenta's ClassTransformation lead, >5 SE) and which are within noise
(Hillstrom/X5/MegaFon tops). Backs the manuscript's "fold-level standard errors
overlap at 10K" sentence and the RESULTS.md annotations.

Emits results/findings_resolution.md.

Usage: python scripts/leaderboard_resolution.py
"""

from __future__ import annotations

import glob
from pathlib import Path

import numpy as np
import pandas as pd

OUT = Path("results/findings_resolution.md")

PANELS = {
    "hillstrom (full 64K -- not capped)": "results/hillstrom__{m}.parquet",
    "lenta (10K cap of 687K)": "results/lenta__{m}.parquet",
    "x5 (10K cap of 200K)": "results/x5__{m}.parquet",
    "megafon (10K cap of 600K)": "results/megafon__{m}.parquet",
    "criteo_1m (10K cap of 1M tier)": "results_criteo/criteo_1m__{m}.parquet",
    "criteo_100k (100K probe, six learners)": "results_criteo100k/criteo_100k__{m}.parquet",
}


def rows_for(pattern: str):
    rows = []
    for f in glob.glob(pattern.replace("{m}", "*")):
        if "__summary" in f:
            continue
        d = pd.read_parquet(f)
        m = f.split("__")[-1].replace(".parquet", "")
        q = d["qini"].to_numpy(float)
        rows.append((m, float(q.mean()), float(q.std(ddof=1) / np.sqrt(len(q)))))
    rows.sort(key=lambda r: -r[1])
    return rows


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Leaderboard resolution: fold-level Qini SEs (auto-generated by "
        "scripts/leaderboard_resolution.py)",
        "",
        "z = separation of the leader from each model in combined-SE units; models with",
        "z < 2 are not descriptively resolved from the leader at the evaluated n "
        "(fold SEs are dependent; treat all values as descriptive, not inferential).",
        "",
    ]
    for name, pattern in PANELS.items():
        rows = rows_for(pattern)
        if not rows:
            lines.append(f"## {name}\n\n(absent -- run the corresponding target)\n")
            continue
        top = rows[0]
        within = sum(
            1 for m, mu, se in rows[1:] if (top[1] - mu) / np.sqrt(top[2] ** 2 + se**2) < 2
        )
        lines.append(f"## {name}")
        lines.append("")
        lines.append("| model | qini mean | fold SE | z vs leader |")
        lines.append("|---|---|---|---|")
        for m, mu, se in rows:
            z = (top[1] - mu) / np.sqrt(top[2] ** 2 + se**2) if m != top[0] else 0.0
            tag = "leader" if m == top[0] else f"{z:.1f}"
            lines.append(f"| {m} | {mu:+.2f} | {se:.2f} | {tag} |")
        lines.append("")
        lines.append(f"**{within}/{len(rows) - 1} models within 2 SE of the leader.**")
        lines.append("")
        print(f"{name}: {within}/{len(rows)-1} within 2 SE of leader")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"Saved: {OUT}")

    # Appendix table for the manuscript: per-model Qini +/- fold SE at the released
    # 10K cap and at the 100K probe (six meta/forest learners; others 10K-only).
    r10 = {m: (mu, se) for m, mu, se in rows_for("results_criteo/criteo_1m__{m}.parquet")}
    r100 = {m: (mu, se) for m, mu, se in rows_for("results_criteo100k/criteo_100k__{m}.parquet")}
    display = {
        "class_transformation": "ClassTrans",
        "causal_forest": "CausalForest",
        "s_learner": "S-Learner",
        "t_learner": "T-Learner",
        "x_learner": "X-Learner",
        "r_learner": "R-Learner",
        "dr_learner": "DR-Learner",
        "solo_model": "SoloModel",
        "two_model": "TwoModel",
        "uplift_rf_kl": "UpliftRF-KL",
        "uplift_rf_ed": "UpliftRF-ED",
        "uplift_rf_chi": "UpliftRF-Chi",
    }
    if r10:
        tex = Path("results/tables/tab29_criteo.tex")
        order = sorted(r10, key=lambda m: -r10[m][0])
        body = []
        for m in order:
            mu, se = r10[m]
            c100 = f"${r100[m][0]:+.1f} \\pm {r100[m][1]:.1f}$" if m in r100 else "---"
            nm = display.get(m, m.replace("_", r"\_"))
            body.append(f"{nm} & ${mu:+.2f} \\pm {se:.2f}$ & {c100} \\\\")
        tex.write_text(
            "% auto-generated by scripts/leaderboard_resolution.py\n"
            "\\begin{tabular}{lrr}\n\\toprule\n"
            "Model & Qini (10K cap) $\\pm$ fold SE & Qini (100K probe) $\\pm$ fold SE \\\\\n"
            "\\midrule\n" + "\n".join(body) + "\n\\bottomrule\n\\end{tabular}\n"
        )
        print(f"Saved: {tex}")


if __name__ == "__main__":
    main()
