"""Fixed-hyperparameter (no-tune) F1 sensitivity: is the Qini/AUUC separation an
artifact of the Qini-tuned candidate panel?

The released protocol tunes every estimator by inner-fold validation Qini, so the
candidate panel every metric scores was itself selected under one of the metrics we
scrutinize (a disclosed limitation). This audit reruns the primary continuous panel
(the 10 IHDP splits, the six applicable estimators, identical 3x3 fold protocol)
with `tuning.enabled=false` -- every estimator at its default hyperparameters, no
inner search at all -- and recomputes the F1 statistics:

  per-split Spearman (across models) of Qini / AUUC / uplift-at-k vs -sqrt(PEHE),
  their means over the 10 splits with dataset-level bootstrap CIs, and the paired
  AUUC-over-Qini gap (the load-bearing F1 quantity).

If the separation persists with no tuning in the loop, F1 is not induced by the
Qini-tuned search. Emits `results/tables/tab21_notune.tex`.

Needs `results_notune/` (`make repro-f1-notune`); on a fresh clone without it the
script emits placeholder macros pointing at the make target, so the paper still
builds.

Usage: python scripts/notune_sensitivity.py
"""

from __future__ import annotations

import glob
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import spearmanr

SEED = 42
IHDP = [f"ihdp_s{i}" for i in range(10)]
NOTUNE_DIR = Path("results_notune")
OUT = Path("results/tables/tab21_notune.tex")
# Second arm (R14): tuning ON but by AUUC instead of Qini. Library defaults are not a
# neutral panel either, so the sharper test of "is F1 induced by Qini-tuned selection?" is
# to tune by the competing metric at the same budget.
AUUC_DIR = Path("results_auuctune")
OUT_AUUC = Path("results/tables/tab23_auuctune.tex")
# The released (Qini-tuned) arm, recomputed through this same code path so that all three
# rows of the tuning-arms table carry symmetric CIs on BOTH metrics. The main-run parquets
# live in results/ (plus the extension dirs, which cover splits >= 10 and are filtered out
# by the IHDP list below).
RELEASED_DIRS = ["results"]
OUT_REL = Path("results/tables/tab24_released_arm.tex")

# metric column -> higher-is-better orientation
METRICS = {"qini_mean": True, "auuc_mean": True, "uplift_at_k_mean": True}


def _rho(g: pd.DataFrame, col: str, higher: bool) -> float:
    """Spearman across models of an oriented metric vs -sqrt(PEHE) (complete case)."""
    sub = g.dropna(subset=[col, "pehe_mean"])
    if len(sub) < 4:
        return float("nan")
    a = sub[col] if higher else -sub[col]
    return float(spearmanr(a, -sub["pehe_mean"]).correlation)


def _boot_ci(vals, n=10000):
    rng = np.random.default_rng(SEED)
    v = np.asarray(vals, float)
    v = v[~np.isnan(v)]
    boot = np.array([rng.choice(v, len(v), replace=True).mean() for _ in range(n)])
    return float(v.mean()), float(np.percentile(boot, 2.5)), float(np.percentile(boot, 97.5))


def _panel(files):
    """Per-split alignment stats for one results directory."""
    summ = pd.concat([pd.read_parquet(f) for f in files], ignore_index=True)
    summ = summ[summ.dataset.isin(IHDP)]
    rows = []
    for ds in IHDP:
        g = summ[summ.dataset == ds]
        r = {"dataset": ds, "n_models": int(g.pehe_mean.notna().sum())}
        for col, hi in METRICS.items():
            r[col] = _rho(g, col, hi)
        r["gap"] = r["auuc_mean"] - r["qini_mean"]
        rows.append(r)
    return pd.DataFrame(rows)


def auuc_arm():
    """The AUUC-tuned arm: same panel and budget, inner objective = AUUC."""
    files = sorted(glob.glob(str(AUUC_DIR / "*__summary.parquet")))
    if not files:
        if OUT_AUUC.exists():
            print(
                f"skipping AUUC-tuned arm: {AUUC_DIR}/ missing; keeping committed "
                f"{OUT_AUUC} (run `make repro-f1-auuctune`)"
            )
            return
        print(f"skipping AUUC-tuned arm: {AUUC_DIR}/ missing (run `make repro-f1-auuctune`)")
        ph = r"n/a\thanks{run \texttt{make repro-f1-auuctune}}"
        OUT_AUUC.write_text(
            "\n".join(
                ["% auto-generated by scripts/notune_sensitivity.py (AUUC-tuned arm)"]
                + [
                    f"\\newcommand{{\\{n}}}{{{ph}}}"
                    for n in (
                        "atQini",
                        "atQiniLo",
                        "atQiniHi",
                        "atAuuc",
                        "atAuucLo",
                        "atAuucHi",
                        "atDelta",
                        "atDeltaLo",
                        "atDeltaHi",
                        "atPos",
                        "atNModels",
                    )
                ]
            )
            + "\n"
        )
        return

    df = _panel(files)
    q = _boot_ci(df["qini_mean"])
    a = _boot_ci(df["auuc_mean"])
    d = _boot_ci(df["gap"])
    pos = int((df["gap"] > 0).sum())
    nm = int(df["n_models"].min())
    print("\n=== AUUC-tuned arm (inner objective = AUUC, B=10), 10 IHDP splits ===")
    print(f"  models per split (min): {nm}")
    print(f"  rho(Qini, -sqrtPEHE)      = {q[0]:+.2f} [{q[1]:+.2f},{q[2]:+.2f}]")
    print(f"  rho(AUUC, -sqrtPEHE)      = {a[0]:+.2f} [{a[1]:+.2f},{a[2]:+.2f}]")
    print(
        f"  paired AUUC-over-Qini gap = {d[0]:+.2f} [{d[1]:+.2f},{d[2]:+.2f}] "
        f"(positive on {pos}/10)"
    )

    def f(x):
        return f"{x:+.2f}"

    OUT_AUUC.write_text(
        "\n".join(
            [
                "% auto-generated by scripts/notune_sensitivity.py (AUUC-tuned arm)",
                f"\\newcommand{{\\atQini}}{{{f(q[0])}}}",
                f"\\newcommand{{\\atQiniLo}}{{{f(q[1])}}}",
                f"\\newcommand{{\\atQiniHi}}{{{f(q[2])}}}",
                f"\\newcommand{{\\atAuuc}}{{{f(a[0])}}}",
                f"\\newcommand{{\\atAuucLo}}{{{f(a[1])}}}",
                f"\\newcommand{{\\atAuucHi}}{{{f(a[2])}}}",
                f"\\newcommand{{\\atDelta}}{{{f(d[0])}}}",
                f"\\newcommand{{\\atDeltaLo}}{{{f(d[1])}}}",
                f"\\newcommand{{\\atDeltaHi}}{{{f(d[2])}}}",
                f"\\newcommand{{\\atPos}}{{{pos}}}",
                f"\\newcommand{{\\atNModels}}{{{nm}}}",
            ]
        )
        + "\n"
    )
    print(f"Saved: {OUT_AUUC}")


def released_arm():
    """Recompute the released Qini-tuned arm with the same estimator and CI conventions."""
    files = []
    for d in RELEASED_DIRS:
        files += [f for f in glob.glob(f"{d}/ihdp_s*__summary.parquet")]
    if not files:
        print("skipping released arm: results/ihdp_s*__summary.parquet missing")
        return
    df = _panel(sorted(files))
    q = _boot_ci(df["qini_mean"])
    a = _boot_ci(df["auuc_mean"])
    d = _boot_ci(df["gap"])
    pos = int((df["gap"] > 0).sum())
    nm = int(df["n_models"].min())
    print("\n=== Released arm (inner objective = Qini, B=10), 10 IHDP splits ===")
    print(f"  models per split (min): {nm}")
    print(f"  rho(Qini, -sqrtPEHE)      = {q[0]:+.2f} [{q[1]:+.2f},{q[2]:+.2f}]")
    print(f"  rho(AUUC, -sqrtPEHE)      = {a[0]:+.2f} [{a[1]:+.2f},{a[2]:+.2f}]")
    print(
        f"  paired AUUC-over-Qini gap = {d[0]:+.2f} [{d[1]:+.2f},{d[2]:+.2f}] "
        f"(positive on {pos}/10)"
    )

    def f(x):
        return f"{x:+.2f}"

    OUT_REL.write_text(
        "\n".join(
            [
                "% auto-generated by scripts/notune_sensitivity.py (released Qini-tuned arm)",
                f"\\newcommand{{\\relQini}}{{{f(q[0])}}}",
                f"\\newcommand{{\\relQiniLo}}{{{f(q[1])}}}",
                f"\\newcommand{{\\relQiniHi}}{{{f(q[2])}}}",
                f"\\newcommand{{\\relAuuc}}{{{f(a[0])}}}",
                f"\\newcommand{{\\relAuucLo}}{{{f(a[1])}}}",
                f"\\newcommand{{\\relAuucHi}}{{{f(a[2])}}}",
                f"\\newcommand{{\\relDelta}}{{{f(d[0])}}}",
                f"\\newcommand{{\\relDeltaLo}}{{{f(d[1])}}}",
                f"\\newcommand{{\\relDeltaHi}}{{{f(d[2])}}}",
                f"\\newcommand{{\\relPos}}{{{pos}}}",
            ]
        )
        + "\n"
    )
    print(f"Saved: {OUT_REL}")


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    files = sorted(glob.glob(str(NOTUNE_DIR / "*__summary.parquet")))
    macros = ["% auto-generated by scripts/notune_sensitivity.py"]

    if not files:
        # Never clobber a committed table with placeholders: on a clone that has the
        # parquets removed but the table present, the real numbers must survive.
        if OUT.exists():
            print(
                f"skipping notune_sensitivity: {NOTUNE_DIR}/ missing; keeping the "
                f"committed {OUT} (run `make repro-f1-notune` to regenerate)"
            )
            auuc_arm()
            released_arm()
            return
        print(
            f"skipping notune_sensitivity: {NOTUNE_DIR}/ missing "
            "(run `make repro-f1-notune`); emitting placeholders"
        )
        ph = r"n/a\thanks{run \texttt{make repro-f1-notune}}"
        for name in (
            "notuneQini",
            "notuneQiniLo",
            "notuneQiniHi",
            "notuneAuuc",
            "notuneAuucLo",
            "notuneAuucHi",
            "notuneUk",
            "notuneUkLo",
            "notuneUkHi",
            "notuneDelta",
            "notuneDeltaLo",
            "notuneDeltaHi",
            "notunePos",
            "notuneNModels",
        ):
            macros.append(f"\\newcommand{{\\{name}}}{{{ph}}}")
        OUT.write_text("\n".join(macros) + "\n")
        return

    summ = pd.concat([pd.read_parquet(f) for f in files], ignore_index=True)
    summ = summ[summ.dataset.isin(IHDP)]

    rows = []
    for ds in IHDP:
        g = summ[summ.dataset == ds]
        r = {"dataset": ds, "n_models": int(g.pehe_mean.notna().sum())}
        for col, hi in METRICS.items():
            r[col] = _rho(g, col, hi)
        r["gap"] = r["auuc_mean"] - r["qini_mean"]
        rows.append(r)
    df = pd.DataFrame(rows)

    q = _boot_ci(df["qini_mean"])
    a = _boot_ci(df["auuc_mean"])
    u = _boot_ci(df["uplift_at_k_mean"])
    d = _boot_ci(df["gap"])
    pos = int((df["gap"] > 0).sum())
    nm = int(df["n_models"].min())

    print("=== Fixed-hyperparameter (no-tune) F1 sensitivity, 10 IHDP splits ===")
    print(f"  models per split (min): {nm}")
    print(f"  rho(Qini, -sqrtPEHE)      = {q[0]:+.2f} [{q[1]:+.2f},{q[2]:+.2f}]")
    print(f"  rho(AUUC, -sqrtPEHE)      = {a[0]:+.2f} [{a[1]:+.2f},{a[2]:+.2f}]")
    print(f"  rho(uplift@k, -sqrtPEHE)  = {u[0]:+.2f} [{u[1]:+.2f},{u[2]:+.2f}]")
    print(
        f"  paired AUUC-over-Qini gap = {d[0]:+.2f} [{d[1]:+.2f},{d[2]:+.2f}] "
        f"(positive on {pos}/10 splits)"
    )
    print(df[["dataset", "qini_mean", "auuc_mean", "gap"]].to_string(index=False))

    def f(x):
        return f"{x:+.2f}"

    macros += [
        f"\\newcommand{{\\notuneQini}}{{{f(q[0])}}}",
        f"\\newcommand{{\\notuneQiniLo}}{{{f(q[1])}}}",
        f"\\newcommand{{\\notuneQiniHi}}{{{f(q[2])}}}",
        f"\\newcommand{{\\notuneAuuc}}{{{f(a[0])}}}",
        f"\\newcommand{{\\notuneAuucLo}}{{{f(a[1])}}}",
        f"\\newcommand{{\\notuneAuucHi}}{{{f(a[2])}}}",
        f"\\newcommand{{\\notuneUk}}{{{f(u[0])}}}",
        f"\\newcommand{{\\notuneUkLo}}{{{f(u[1])}}}",
        f"\\newcommand{{\\notuneUkHi}}{{{f(u[2])}}}",
        f"\\newcommand{{\\notuneDelta}}{{{f(d[0])}}}",
        f"\\newcommand{{\\notuneDeltaLo}}{{{f(d[1])}}}",
        f"\\newcommand{{\\notuneDeltaHi}}{{{f(d[2])}}}",
        f"\\newcommand{{\\notunePos}}{{{pos}}}",
        f"\\newcommand{{\\notuneNModels}}{{{nm}}}",
    ]
    OUT.write_text("\n".join(macros) + "\n")
    print(f"Saved: {OUT}")
    auuc_arm()
    released_arm()


if __name__ == "__main__":
    main()
