"""Impact of the EconML treatment-nuisance fix on F1 (external audits, R26/R27).

Releases up to v1.3.0 passed an LGBMRegressor as ``model_t`` to NonParamDML and
CausalForestDML with ``discrete_treatment=True``; EconML requires a classifier there.
As of v1.4.1 every released parquet is regenerated under the corrected nuisance
(R-Learner and CausalForest are the only estimators that touch ``model_t``), and the
pre-fix main-panel cells are archived in ``results_pre141/`` so this delta stays
reproducible.

This script reconstructs the <=v1.4.0 panel by swapping the archived pre-fix cells
into the current (corrected) panel and reports both panels' paired AUUC-over-Qini
gaps plus the CausalForest cell-level rank agreement across the fix.

Usage: python scripts/nuisance_fix_check.py
"""

from __future__ import annotations

import glob
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import spearmanr

SEED = 42
OUT = Path("results/tables/tab28_nuisancefix.tex")
PRE = Path("results_pre141")
MODELS = ["s_learner", "t_learner", "x_learner", "r_learner", "dr_learner", "causal_forest"]
FIXED = ["r_learner", "causal_forest"]


def _boot_ci(vals, n=10000):
    rng = np.random.default_rng(SEED)
    v = np.asarray(vals, float)
    boot = np.array([rng.choice(v, len(v), replace=True).mean() for _ in range(n)])
    return float(v.mean()), float(np.percentile(boot, 2.5)), float(np.percentile(boot, 97.5))


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    pre_files = glob.glob(str(PRE / "ihdp_s*__summary.parquet"))
    if not pre_files:
        print("skipping nuisance_fix_check: results_pre141/ missing")
        if not OUT.exists():
            OUT.write_text("% nuisance_fix_check skipped: results_pre141/ missing\n")
        return
    cur = pd.concat([pd.read_parquet(f) for f in glob.glob("results/ihdp_s*__summary.parquet")])
    pre = pd.concat([pd.read_parquet(f) for f in pre_files])

    gaps = {"corrected": [], "prefix_nuisance": []}
    for i in range(10):
        ds = f"ihdp_s{i}"
        g = (
            cur[(cur.dataset == ds) & cur.model.isin(MODELS)]
            .set_index("model")[["qini_mean", "auuc_mean", "pehe_mean"]]
            .copy()
        )
        gg = g.copy()  # reconstruct the <=v1.4.0 panel: swap the archived cells back in
        for m in FIXED:
            row = pre[(pre.dataset == ds) & (pre.model == m)]
            if len(row):
                gg.loc[m] = row[["qini_mean", "auuc_mean", "pehe_mean"]].iloc[0].values
        for lbl, fr in (("corrected", g), ("prefix_nuisance", gg)):
            q = spearmanr(fr.qini_mean, -fr.pehe_mean).correlation
            a = spearmanr(fr.auuc_mean, -fr.pehe_mean).correlation
            gaps[lbl].append(a - q)
    fix = _boot_ci(gaps["corrected"])
    old = _boot_ci(gaps["prefix_nuisance"])
    cf_cur = cur[cur.model == "causal_forest"].set_index("dataset").pehe_mean.sort_index()
    cf_pre = pre[pre.model == "causal_forest"].set_index("dataset").pehe_mean.sort_index()
    cf_corr = spearmanr(cf_pre, cf_cur.loc[cf_pre.index]).correlation

    print("=== F1 across the treatment-nuisance fix (classifier model_t, v1.4.1) ===")
    print(f"  corrected (released) panel gap: {fix[0]:+.2f} [{fix[1]:+.2f},{fix[2]:+.2f}]")
    print(f"  pre-fix (<=v1.4.0) panel gap:   {old[0]:+.2f} [{old[1]:+.2f},{old[2]:+.2f}]")
    print(f"  causal_forest cell-level Spearman across the fix: {cf_corr:+.2f}")

    def f(x):
        return f"{x:+.2f}"

    OUT.write_text(
        "\n".join(
            [
                "% auto-generated by scripts/nuisance_fix_check.py",
                f"\\newcommand{{\\nfixGap}}{{{f(fix[0])}}}",
                f"\\newcommand{{\\nfixGapLo}}{{{f(fix[1])}}}",
                f"\\newcommand{{\\nfixGapHi}}{{{f(fix[2])}}}",
                f"\\newcommand{{\\nfixOldGap}}{{{f(old[0])}}}",
                f"\\newcommand{{\\nfixOldGapLo}}{{{f(old[1])}}}",
                f"\\newcommand{{\\nfixOldGapHi}}{{{f(old[2])}}}",
                f"\\newcommand{{\\nfixCfCorr}}{{{f(cf_corr)}}}",
            ]
        )
        + "\n"
    )
    print(f"Saved: {OUT}")


if __name__ == "__main__":
    main()
