"""Impact of the EconML treatment-nuisance fix on F1 (external audit, P1-2).

Releases up to v1.3.0 passed an LGBMRegressor as ``model_t`` to NonParamDML and
CausalForestDML with ``discrete_treatment=True``; EconML requires a classifier there.
The code is fixed; this script measures what the fix changes by rerunning the two
affected estimators on the 10 primary IHDP splits (``results_nuisancefix/``) and
swapping the corrected cells into the released panel.

Verdict (committed run): CausalForest is essentially unchanged (cell-level Spearman
+1.00 vs released), the R-Learner shifts mildly, and the swapped panel's paired
AUUC-over-Qini gap is within the tuning-arm range -- F1 is robust to the fix. The
released headline parquets retain the regressor-nuisance candidates (documented in
PROVENANCE.md); a full rerun under the corrected nuisance is planned next release.

Usage: python scripts/nuisance_fix_check.py
"""

from __future__ import annotations

import glob
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import spearmanr

SEED = 42
OUT = Path("results/tables/tab28_nuisancefix.tex")
MODELS = ["s_learner", "t_learner", "x_learner", "r_learner", "dr_learner", "causal_forest"]
FIXED = ["r_learner", "causal_forest"]


def _boot_ci(vals, n=10000):
    rng = np.random.default_rng(SEED)
    v = np.asarray(vals, float)
    boot = np.array([rng.choice(v, len(v), replace=True).mean() for _ in range(n)])
    return float(v.mean()), float(np.percentile(boot, 2.5)), float(np.percentile(boot, 97.5))


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    fixed_files = glob.glob("results_nuisancefix/*__summary.parquet")
    if not fixed_files:
        print("skipping nuisance_fix_check: results_nuisancefix/ missing")
        if not OUT.exists():
            OUT.write_text("% nuisance_fix_check skipped: results_nuisancefix/ missing\n")
        return
    old = pd.concat([pd.read_parquet(f) for f in glob.glob("results/ihdp_s*__summary.parquet")])
    new = pd.concat([pd.read_parquet(f) for f in fixed_files])

    gaps = {"released": [], "fixed": []}
    for i in range(10):
        ds = f"ihdp_s{i}"
        g = (
            old[(old.dataset == ds) & old.model.isin(MODELS)]
            .set_index("model")[["qini_mean", "auuc_mean", "pehe_mean"]]
            .copy()
        )
        gg = g.copy()
        for m in FIXED:
            row = new[(new.dataset == ds) & (new.model == m)]
            if len(row):
                gg.loc[m] = row[["qini_mean", "auuc_mean", "pehe_mean"]].iloc[0].values
        for lbl, fr in (("released", g), ("fixed", gg)):
            q = spearmanr(fr.qini_mean, -fr.pehe_mean).correlation
            a = spearmanr(fr.auuc_mean, -fr.pehe_mean).correlation
            gaps[lbl].append(a - q)
    rel = _boot_ci(gaps["released"])
    fix = _boot_ci(gaps["fixed"])
    cf_old = old[old.model == "causal_forest"].set_index("dataset").pehe_mean.sort_index()
    cf_new = new[new.model == "causal_forest"].set_index("dataset").pehe_mean.sort_index()
    cf_corr = spearmanr(cf_old.loc[cf_new.index], cf_new).correlation

    print("=== F1 under the corrected treatment nuisance (classifier model_t) ===")
    print(f"  released panel gap: {rel[0]:+.2f} [{rel[1]:+.2f},{rel[2]:+.2f}]")
    print(f"  fixed-cells  gap:   {fix[0]:+.2f} [{fix[1]:+.2f},{fix[2]:+.2f}]")
    print(f"  causal_forest cell-level Spearman vs released: {cf_corr:+.2f}")

    def f(x):
        return f"{x:+.2f}"

    OUT.write_text(
        "\n".join(
            [
                "% auto-generated by scripts/nuisance_fix_check.py",
                f"\\newcommand{{\\nfixGap}}{{{f(fix[0])}}}",
                f"\\newcommand{{\\nfixGapLo}}{{{f(fix[1])}}}",
                f"\\newcommand{{\\nfixGapHi}}{{{f(fix[2])}}}",
                f"\\newcommand{{\\nfixCfCorr}}{{{f(cf_corr)}}}",
            ]
        )
        + "\n"
    )
    print(f"Saved: {OUT}")


if __name__ == "__main__":
    main()
