"""R19 analyses: two evidence holes closed, a funnel-free restatement of F1, and a
pre-specified mechanism test.

(1) AUUC on ACIC. F1 is the paired AUUC-over-Qini gap, yet the ACIC boundary passage
    reported Qini, uplift@k, and RATE-AUTOC without AUUC -- the load-bearing statistic
    was missing from half the boundary argument. Computed here from the committed
    results_acic/ parquets.

(2) The all-100 exclusion ladder. Exclusion sensitivity existed only for the 10-split
    panel, where the DR+R-excluded CI was marginal (+0.56 [+0.10,+1.00]). At n=100 the
    same ladder is decisive.

(3) Pairwise concordance. Every per-realization Spearman is a 6-point (4 under
    exclusion) rank correlation. Restating F1 as pairwise concordance -- for each
    realization and model pair, does the metric order the pair as -sqrt(PEHE) does? --
    gives 1,500 binary comparisons with a realization-level bootstrap and no small-n
    funnel. (Tuning configs were deliberately NOT promoted to candidates: configs of one
    learner are near-duplicates and would inflate n dishonestly.)

(4) PRE-SPECIFIED mechanism test (direction and specification fixed before looking):
    Lemma 5.2's interleaving term implies the composite R = |ATE|/SD(tau) x
    sqrt((1-pi1)/pi1) should predict WORSE Qini alignment and a LARGER gap. Tested
    within-family only (cross-family pooling is confounded by family membership).
    Outcome, applied per the pre-commitment: the Qini-alignment half CONFIRMS in both
    families independently; the gap half is NULL in both, and R also predicts AUUC's
    alignment -- so R is a replicated, theory-derived *difficulty* covariate, and the
    mechanism for the metric-specific gap remains open. The oracle SD(tau) is used to
    identify; a Section-6 diagnostic would need the estimable proxy (future work).

Emits results/tables/tab26_r19.tex. Needs results/, results_m1ext/, results_ihdpval/,
results_acic/ parquets and cached IHDP/ACIC data.

Usage: python scripts/r19_analyses.py
"""

from __future__ import annotations

import glob
import itertools
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import spearmanr

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from uplift_bench.data.registry import load_dataset  # noqa: E402

SEED = 42
OUT = Path("results/tables/tab26_r19.tex")
IHDP_DIRS = ["results", "results_m1ext", "results_ihdpval"]


def _boot_mean(v, n=10000, seed=SEED):
    rng = np.random.default_rng(seed)
    v = np.asarray(v, float)
    v = v[~np.isnan(v)]
    b = np.array([v[rng.integers(0, len(v), len(v))].mean() for _ in range(n)])
    return float(v.mean()), float(np.percentile(b, 2.5)), float(np.percentile(b, 97.5))


def _boot_corr(x, y, n=5000, seed=SEED):
    rng = np.random.default_rng(seed)
    x, y = np.asarray(x, float), np.asarray(y, float)
    ok = ~(np.isnan(x) | np.isnan(y))
    x, y = x[ok], y[ok]
    pt = float(spearmanr(x, y).correlation)
    b = []
    for _ in range(n):
        i = rng.integers(0, len(x), len(x))
        r = spearmanr(x[i], y[i]).correlation
        if not np.isnan(r):
            b.append(r)
    return pt, float(np.percentile(b, 2.5)), float(np.percentile(b, 97.5))


def _load(dirs, pattern):
    frames = []
    for d in dirs:
        frames += [pd.read_parquet(f) for f in glob.glob(f"{d}/{pattern}")]
    return pd.concat(frames, ignore_index=True)


def _align(summ, name, exclude=()):
    g = (summ[(summ.dataset == name) & (~summ.model.isin(exclude))]
         .groupby("model")[["qini_mean", "auuc_mean", "pehe_mean"]]
         .mean().dropna(subset=["pehe_mean"]))
    if len(g) < 4:
        return None
    q = float(spearmanr(g.qini_mean, -g.pehe_mean).correlation)
    a = float(spearmanr(g.auuc_mean, -g.pehe_mean).correlation)
    return q, a


def fmt(x, d=2):
    return f"{x:+.{d}f}"


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    macros = ["% auto-generated by scripts/r19_analyses.py"]

    needed = [Path("results/master_raw.parquet"), Path("results_acic")]
    if any(not p.exists() for p in needed):
        print("skipping r19_analyses: needs results/ + results_acic/ parquets")
        if not OUT.exists():
            ph = r"n/a\thanks{run the benchmark tiers; see README}"
            names = ("acicAuucMOne acicAuucMOneLo acicAuucMOneHi acicGap acicGapLo acicGapHi "
                     "acicGapPos eHundDeltaExDR eHundDeltaExDRLo eHundDeltaExDRHi "
                     "eHundDeltaExDRR eHundDeltaExDRRLo eHundDeltaExDRRHi concQini concQiniLo "
                     "concQiniHi concAuuc concAuucLo concAuucHi concN mechQiniIhdp "
                     "mechQiniIhdpLo mechQiniIhdpHi mechQiniAcic mechQiniAcicLo mechQiniAcicHi "
                     "mechGapIhdp mechGapIhdpLo mechGapIhdpHi mechGapAcic mechGapAcicLo "
                     "mechGapAcicHi mechAuucIhdp mechAuucIhdpLo mechAuucIhdpHi").split()
            OUT.write_text("\n".join(macros + [f"\\newcommand{{\\{n}}}{{{ph}}}" for n in names]) + "\n")
        return

    # ---- (1) AUUC on ACIC + the paired gap --------------------------------------
    sa = _load(["results_acic"], "acic_*__summary.parquet")
    anames = sorted(sa.dataset.unique())
    rows = [(_align(sa, d)) for d in anames]
    rows = [r for r in rows if r]
    aq = [r[0] for r in rows]
    aa = [r[1] for r in rows]
    agap = [a - q for q, a in rows]
    A = _boot_mean(aa)
    G = _boot_mean(agap)
    print(f"(1) ACIC ({len(rows)} instances): rho(AUUC) {fmt(A[0])} [{fmt(A[1])},{fmt(A[2])}]  "
          f"gap {fmt(G[0])} [{fmt(G[1])},{fmt(G[2])}], positive {int(np.sum(np.array(agap)>0))}/{len(rows)}")
    macros += [f"\\newcommand{{\\acicAuucMOne}}{{{fmt(A[0])}}}",
               f"\\newcommand{{\\acicAuucMOneLo}}{{{fmt(A[1])}}}",
               f"\\newcommand{{\\acicAuucMOneHi}}{{{fmt(A[2])}}}",
               f"\\newcommand{{\\acicGap}}{{{fmt(G[0])}}}",
               f"\\newcommand{{\\acicGapLo}}{{{fmt(G[1])}}}",
               f"\\newcommand{{\\acicGapHi}}{{{fmt(G[2])}}}",
               f"\\newcommand{{\\acicGapPos}}{{{int(np.sum(np.array(agap)>0))}}}"]

    # ---- (2) all-100 exclusion ladder --------------------------------------------
    si = _load(IHDP_DIRS, "ihdp_s*__summary.parquet")
    names = [f"ihdp_s{i}" for i in range(100)]
    for tag, excl in (("ExDR", {"dr_learner"}), ("ExDRR", {"dr_learner", "r_learner"})):
        gaps = []
        for d in names:
            r = _align(si, d, exclude=excl)
            if r:
                gaps.append(r[1] - r[0])
        m = _boot_mean(gaps)
        print(f"(2) all-100 gap {tag}: {fmt(m[0])} [{fmt(m[1])},{fmt(m[2])}] over {len(gaps)}")
        macros += [f"\\newcommand{{\\eHundDelta{tag}}}{{{fmt(m[0])}}}",
                   f"\\newcommand{{\\eHundDelta{tag}Lo}}{{{fmt(m[1])}}}",
                   f"\\newcommand{{\\eHundDelta{tag}Hi}}{{{fmt(m[2])}}}"]

    # ---- (3) pairwise concordance -------------------------------------------------
    qr, ar, npairs = [], [], 0
    for d in names:
        g = (si[si.dataset == d].groupby("model")[["qini_mean", "auuc_mean", "pehe_mean"]]
             .mean().dropna(subset=["pehe_mean"]))
        qc = ac = n = 0
        for m1, m2 in itertools.combinations(g.index, 2):
            truth = g.pehe_mean[m1] < g.pehe_mean[m2]
            qc += (g.qini_mean[m1] > g.qini_mean[m2]) == truth
            ac += (g.auuc_mean[m1] > g.auuc_mean[m2]) == truth
            n += 1
        qr.append(qc / n)
        ar.append(ac / n)
        npairs += n
    Q = _boot_mean(qr)
    Au = _boot_mean(ar)
    print(f"(3) concordance over {npairs} pairs: Qini {Q[0]:.3f} [{Q[1]:.3f},{Q[2]:.3f}]  "
          f"AUUC {Au[0]:.3f} [{Au[1]:.3f},{Au[2]:.3f}]")
    macros += [f"\\newcommand{{\\concQini}}{{{Q[0]:.2f}}}",
               f"\\newcommand{{\\concQiniLo}}{{{Q[1]:.2f}}}",
               f"\\newcommand{{\\concQiniHi}}{{{Q[2]:.2f}}}",
               f"\\newcommand{{\\concAuuc}}{{{Au[0]:.2f}}}",
               f"\\newcommand{{\\concAuucLo}}{{{Au[1]:.2f}}}",
               f"\\newcommand{{\\concAuucHi}}{{{Au[2]:.2f}}}",
               f"\\newcommand{{\\concN}}{{{npairs}}}"]

    # ---- (4) pre-specified composite mechanism test -------------------------------
    def composite_ihdp(i):
        ds = load_dataset("ihdp", split_idx=i)
        tau = ds.ite.iloc[:, 0].to_numpy(float)
        p = ds.treatment.to_numpy().mean()
        return abs(tau.mean()) / tau.std() * np.sqrt((1 - p) / p)

    Ri = [composite_ihdp(i) for i in range(100)]
    ali = [_align(si, d) for d in names]
    qi = [a[0] if a else np.nan for a in ali]
    gi = [a[1] - a[0] if a else np.nan for a in ali]
    ai_ = [a[1] if a else np.nan for a in ali]
    mqi = _boot_corr(Ri, qi)
    mgi = _boot_corr(Ri, gi)
    mai = _boot_corr(Ri, ai_)

    Ra = []
    for d in anames:
        m = re.match(r"acic_s(\d+)r(\d+)", d)
        ds = load_dataset("acic2016", setting=int(m.group(1)), replicate=int(m.group(2)))
        tau = ds.ite.iloc[:, 0].to_numpy(float)
        p = ds.treatment.to_numpy().mean()
        Ra.append(abs(tau.mean()) / tau.std() * np.sqrt((1 - p) / p))
    mqa = _boot_corr(Ra, aq)
    mga = _boot_corr(Ra, agap)
    maa = _boot_corr(Ra, aa)

    # Cross-family ordering: does per-family median R track the gap gradient? Three
    # ordered medians alone is a 1-in-6 chance event, so this is reported as a candidate
    # separating property, never as a mechanism (that needs the committed controlled sweep).
    Rr = [None] * 10
    for s in range(10):
        ds = load_dataset("revenue_synthetic", seed=s)
        tau = ds.ite.iloc[:, 0].to_numpy(float)
        pr = ds.treatment.to_numpy().mean()
        Rr[s] = abs(tau.mean()) / tau.std() * np.sqrt((1 - pr) / pr)
    med = {"rMedIhdp": np.median(Ri), "rMedAcic": np.median(Ra), "rMedRev": np.median(Rr)}
    print(f"    per-family median R: IHDP {med['rMedIhdp']:.2f} | ACIC {med['rMedAcic']:.2f} "
          f"| Rev-Synth {med['rMedRev']:.2f}  (gaps +0.56 / +0.12 / -0.14)")

    print("(4) composite R = |ATE|/SD(tau) x sqrt((1-pi1)/pi1), pre-specified:")
    print(f"    IHDP: corr(R,Qini) {fmt(mqi[0])} [{fmt(mqi[1])},{fmt(mqi[2])}]  "
          f"corr(R,gap) {fmt(mgi[0])} [{fmt(mgi[1])},{fmt(mgi[2])}]  "
          f"corr(R,AUUC) {fmt(mai[0])} [{fmt(mai[1])},{fmt(mai[2])}]")
    print(f"    ACIC: corr(R,Qini) {fmt(mqa[0])} [{fmt(mqa[1])},{fmt(mqa[2])}]  "
          f"corr(R,gap) {fmt(mga[0])} [{fmt(mga[1])},{fmt(mga[2])}]")
    for name, v in (("mechQiniIhdp", mqi), ("mechGapIhdp", mgi), ("mechAuucIhdp", mai),
                    ("mechQiniAcic", mqa), ("mechGapAcic", mga), ("mechAuucAcic", maa)):
        macros += [f"\\newcommand{{\\{name}}}{{{fmt(v[0])}}}",
                   f"\\newcommand{{\\{name}Lo}}{{{fmt(v[1])}}}",
                   f"\\newcommand{{\\{name}Hi}}{{{fmt(v[2])}}}"]

    for k, v in med.items():
        macros.append(f"\\newcommand{{\\{k}}}{{{v:.2f}}}")

    # ---- (5) proxy computability of R (reviewer-requested; guard on prediction stores) ----
    # Proxy: |mean(pred tau)| / SD(pred tau) x sqrt((1-pi1)/pi1), pooled across candidates.
    # Two variants: all six candidates, and the four numerically stable learners -- the
    # all-six variant fails on IHDP because DR/R prediction blow-ups dominate SD(pred tau).
    import glob as _g

    from scipy.stats import spearmanr as _sp
    STABLE = {"s_learner", "t_learner", "x_learner", "causal_forest"}
    SIX = STABLE | {"r_learner", "dr_learner"}

    def _proxy(fl, pi1, keep):
        taus = []
        for f in fl:
            d = pd.read_parquet(f, columns=["model", "pred"])
            if d.model.iloc[0] in keep:
                taus.append(d["pred"].to_numpy(float))
        v = np.concatenate(taus)
        return abs(v.mean()) / v.std() * np.sqrt((1 - pi1) / pi1)

    if _g.glob("results_r4pred/predictions/ihdp_s*__pred.parquet") and \
       _g.glob("results_acic/predictions/acic_*__pred.parquet"):
        px = {}
        for fam, pat, loader in (
            ("Ihdp", "results_r4pred/predictions/ihdp_s%d__*__pred.parquet",
             lambda i: load_dataset("ihdp", split_idx=i)),
        ):
            oc, p6, p4 = [], [], []
            for i in range(100):
                fl = _g.glob(pat % i)
                if not fl:
                    continue
                ds = loader(i)
                tau = ds.ite.iloc[:, 0].to_numpy(float)
                p1 = ds.treatment.to_numpy().mean()
                oc.append(abs(tau.mean()) / tau.std() * np.sqrt((1 - p1) / p1))
                p6.append(_proxy(fl, p1, SIX))
                p4.append(_proxy(fl, p1, STABLE))
            px["proxTrackSix" + fam] = _sp(oc, p6).correlation
            px["proxTrackFour" + fam] = _sp(oc, p4).correlation
            px["proxMedFour" + fam] = np.median(p4)
        oc, p6, p4 = [], [], []
        for d in anames:
            fl = _g.glob(f"results_acic/predictions/{d}__*__pred.parquet")
            if not fl:
                continue
            m = re.match(r"acic_s(\d+)r(\d+)", d)
            ds = load_dataset("acic2016", setting=int(m.group(1)), replicate=int(m.group(2)))
            tau = ds.ite.iloc[:, 0].to_numpy(float)
            p1 = ds.treatment.to_numpy().mean()
            oc.append(abs(tau.mean()) / tau.std() * np.sqrt((1 - p1) / p1))
            p6.append(_proxy(fl, p1, SIX))
            p4.append(_proxy(fl, p1, STABLE))
        px["proxTrackSixAcic"] = _sp(oc, p6).correlation
        px["proxTrackFourAcic"] = _sp(oc, p4).correlation
        px["proxMedFourAcic"] = np.median(p4)
        print("(5) proxy R tracking of oracle R:")
        print(f"    IHDP: all-six {px['proxTrackSixIhdp']:+.2f}  stable-four "
              f"{px['proxTrackFourIhdp']:+.2f} (median {px['proxMedFourIhdp']:.2f})")
        print(f"    ACIC: all-six {px['proxTrackSixAcic']:+.2f}  stable-four "
              f"{px['proxTrackFourAcic']:+.2f} (median {px['proxMedFourAcic']:.2f})")
        for k, v in px.items():
            macros.append(f"\\newcommand{{\\{k}}}{{{v:+.2f}}}" if "Track" in k
                          else f"\\newcommand{{\\{k}}}{{{v:.2f}}}")
    else:
        print("skipping proxy tracking: prediction stores absent")
        for k in ("proxTrackSixIhdp", "proxTrackFourIhdp", "proxMedFourIhdp",
                  "proxTrackSixAcic", "proxTrackFourAcic", "proxMedFourAcic"):
            macros.append(f"\\newcommand{{\\{k}}}{{n/a}}")
    OUT.write_text("\n".join(macros) + "\n")
    print(f"Saved: {OUT}")


if __name__ == "__main__":
    main()
