"""Third continuous family: does F1 replicate on Revenue-Synthetic?

F1 is established on IHDP and absent on the ACIC 2016 validation family, which is a
two-point sample. This script evaluates a third continuous family with known per-unit
effects -- `revenue_synthetic`, whose response surface differs from IHDP's in kind
(lognormal baseline spend with a *multiplicative* treatment effect, so the ITE is itself
heavy-tailed) -- over 10 realizations and the same six estimators, fold protocol, and
tuning budget as the primary panel.

It does NOT replicate, and that is the point of running it. Qini tracks effect accuracy
here on par with AUUC, so the paired AUUC-over-Qini gap is indistinguishable from zero.
Combined with the outcome-kurtosis measurements this falsifies the tail explanation outright
rather than merely failing to support it: the family that fails F1 (IHDP) is mild-tailed,
and the genuinely heavy-tailed family (this one) is fine.

Emits results/tables/tab25_revsynth.tex (macros) and prints the per-realization detail.
Also reports the exclusion sensitivity, so the negative gap cannot be blamed on the
DR-Learner, and the outcome kurtosis of both families, which is the comparison that makes
the tail claim untenable.

Needs `results_revsynth/` (`make repro-f1-revsynth`) and the cached IHDP data.

Usage: python scripts/revsynth_family.py
"""

from __future__ import annotations

import glob
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import kurtosis, spearmanr

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from uplift_bench.data.registry import load_dataset  # noqa: E402

SEED = 42
N_REAL = 10
REV = [f"rev_s{i}" for i in range(N_REAL)]
REV_DIR = Path("results_revsynth")
OUT = Path("results/tables/tab25_revsynth.tex")
MACRO_NAMES = (
    "rsQini",
    "rsQiniLo",
    "rsQiniHi",
    "rsAuuc",
    "rsAuucLo",
    "rsAuucHi",
    "rsDelta",
    "rsDeltaLo",
    "rsDeltaHi",
    "rsPos",
    "rsN",
    "rsNModels",
    "rsKurt",
    "rsKurtLo",
    "rsKurtHi",
    "ihdpKurtMed",
    "rsDeltaExclDR",
    "rsDeltaExclDRR",
)


def _rho(g: pd.DataFrame, col: str) -> float:
    sub = g.dropna(subset=[col, "pehe_mean"])
    if len(sub) < 4:
        return float("nan")
    return float(spearmanr(sub[col], -sub["pehe_mean"]).correlation)


def _boot_ci(vals, n=10000):
    rng = np.random.default_rng(SEED)
    v = np.asarray(vals, float)
    v = v[~np.isnan(v)]
    boot = np.array([rng.choice(v, len(v), replace=True).mean() for _ in range(n)])
    return float(v.mean()), float(np.percentile(boot, 2.5)), float(np.percentile(boot, 97.5))


def _panel(summ: pd.DataFrame, exclude=()) -> pd.DataFrame:
    rows = []
    for ds in REV:
        g = (
            summ[(summ.dataset == ds) & (~summ.model.isin(exclude))]
            .groupby("model")[["qini_mean", "auuc_mean", "uplift_at_k_mean", "pehe_mean"]]
            .mean()
            .dropna(subset=["pehe_mean"])
        )
        if len(g) < 4:
            continue
        q, a = _rho(g, "qini_mean"), _rho(g, "auuc_mean")
        rows.append(
            dict(
                dataset=ds,
                n_models=len(g),
                qini=q,
                auuc=a,
                uk=_rho(g, "uplift_at_k_mean"),
                gap=a - q,
            )
        )
    return pd.DataFrame(rows)


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    files = sorted(glob.glob(str(REV_DIR / "*__summary.parquet")))
    if not files:
        if OUT.exists():
            print(
                f"skipping revsynth_family: {REV_DIR}/ missing; keeping committed {OUT} "
                "(run `make repro-f1-revsynth`)"
            )
            return
        print(f"skipping revsynth_family: {REV_DIR}/ missing (run `make repro-f1-revsynth`)")
        ph = r"n/a\thanks{run \texttt{make repro-f1-revsynth}}"
        OUT.write_text(
            "\n".join(
                ["% auto-generated by scripts/revsynth_family.py"]
                + [f"\\newcommand{{\\{n}}}{{{ph}}}" for n in MACRO_NAMES]
            )
            + "\n"
        )
        return

    summ = pd.concat([pd.read_parquet(f) for f in files], ignore_index=True)
    df = _panel(summ)
    q = _boot_ci(df["qini"])
    a = _boot_ci(df["auuc"])
    d = _boot_ci(df["gap"])
    pos = int((df["gap"] > 0).sum())
    nm = int(df["n_models"].min())

    # Exclusion sensitivity: the negative gap must not be a DR-Learner artifact.
    d_dr = _panel(summ, exclude={"dr_learner"})["gap"].mean()
    d_drr = _panel(summ, exclude={"dr_learner", "r_learner"})["gap"].mean()

    # Tail weight: the comparison that makes the heavy-tail explanation untenable.
    rk = [
        float(kurtosis(load_dataset("revenue_synthetic", seed=s).outcome.to_numpy(float)))
        for s in range(N_REAL)
    ]
    ik = [
        float(kurtosis(load_dataset("ihdp", split_idx=s).outcome.to_numpy(float)))
        for s in range(N_REAL)
    ]

    print(f"=== Third continuous family: Revenue-Synthetic ({len(df)} realizations) ===")
    print(f"  estimators per realization: {nm}")
    print(f"  rho(Qini, -sqrtPEHE)      = {q[0]:+.2f} [{q[1]:+.2f},{q[2]:+.2f}]")
    print(f"  rho(AUUC, -sqrtPEHE)      = {a[0]:+.2f} [{a[1]:+.2f},{a[2]:+.2f}]")
    print(
        f"  paired AUUC-over-Qini gap = {d[0]:+.2f} [{d[1]:+.2f},{d[2]:+.2f}] "
        f"(positive on {pos}/{len(df)})"
    )
    print(f"  gap excluding DR          = {d_dr:+.2f}")
    print(f"  gap excluding DR and R    = {d_drr:+.2f}")
    print(
        f"\n  outcome excess kurtosis, Revenue-Synthetic: median {np.median(rk):+.1f} "
        f"[{min(rk):+.1f},{max(rk):+.1f}]"
    )
    print(
        f"  outcome excess kurtosis, IHDP primary panel: median {np.median(ik):+.1f} "
        f"[{min(ik):+.1f},{max(ik):+.1f}]"
    )
    print("  => the family that fails F1 is the MILD-tailed one.\n")
    print(df[["dataset", "n_models", "qini", "auuc", "gap"]].round(2).to_string(index=False))

    def f(x):
        return f"{x:+.2f}"

    vals = {
        "rsQini": f(q[0]),
        "rsQiniLo": f(q[1]),
        "rsQiniHi": f(q[2]),
        "rsAuuc": f(a[0]),
        "rsAuucLo": f(a[1]),
        "rsAuucHi": f(a[2]),
        "rsDelta": f(d[0]),
        "rsDeltaLo": f(d[1]),
        "rsDeltaHi": f(d[2]),
        "rsPos": str(pos),
        "rsN": str(len(df)),
        "rsNModels": str(nm),
        "rsKurt": f"{np.median(rk):.0f}",
        "rsKurtLo": f"{min(rk):.0f}",
        "rsKurtHi": f"{max(rk):.0f}",
        "ihdpKurtMed": f"{np.median(ik):+.1f}",
        "rsDeltaExclDR": f(d_dr),
        "rsDeltaExclDRR": f(d_drr),
    }
    OUT.write_text(
        "\n".join(
            ["% auto-generated by scripts/revsynth_family.py"]
            + [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in vals.items()]
        )
        + "\n"
    )
    print(f"\nSaved: {OUT}")


if __name__ == "__main__":
    main()
